[package]
name = "projclean"
version = "0.1.0"
edition = "2021"
authors = ["sigoden <sigoden@gmail.com>"]
description = "Project Cleaner"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/sigoden/projclean"
repository = "https://github.com/sigoden/projclean"
autotests = false
categories = ["command-line-utilities"]
keywords = ["command-line", "clean", "cleaner", "project"]

[dependencies]
anyhow = "1"
jwalk = "0.6"
tui = "0.17"
crossterm = "0.22"
clap = "3.1"
cli-table = "0.4"

[profile.release]
lto = true
strip = true
opt-level = "z"
