[package]
name = "projclean"
version = "0.1.0"
edition = "2021"
authors = ["sigoden <sigoden@gmail.com>"]
description = "Project Cleaner"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/sigoden/projclean"
repository = "https://github.com/sigoden/projclean"
autotests = false
categories = ["command-line-utilities"]
keywords = ["command-line", "clean", "cleaner", "project"]

[dependencies]
anyhow = "1.0.56"
jwalk = "0.6.0"
tui = "0.17.0"
crossterm = "0.23.0"
clap = "3.1.6"
glob = "0.3.0"

[profile.release]
lto = true
strip = true
opt-level = "z"
