[package]
name = "projclean"
version = "0.5.0"
edition = "2021"
authors = ["sigoden <sigoden@gmail.com>"]
description = "Project cache & build cleaner"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/sigoden/projclean"
repository = "https://github.com/sigoden/projclean"
autotests = false
categories = ["command-line-utilities"]
keywords = ["command-line", "clean", "tui"]

[dependencies]
anyhow = "1"
jwalk = "0.8.1"
tui = "0.19.0"
crossterm = "0.26.1"
crossbeam-utils = "0.8"
clap = "4.1.8"
regex = { version = "1.5", features = ["std"], default-features = false }
ctrlc = "3.2"
inquire = "0.5.3"

[profile.release]
lto = true
strip = true
opt-level = "z"
