[package]
name = "projclean"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
jwalk = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
tui = "0.17"
crossterm = "0.22"

[profile.release]
lto = true
strip = true
opt-level = "z"